### ISSUE TITLE
Export slices wrong

### ISSUE THREAD

**Issue by fengqinglingyu** [qjebbs/sketch-meaxure#12]
I've got another problem, here is the file:
[test.sketch.zip](https://github.com/qjebbs/sketch-meaxure/files/4763815/test.sketch.zip)
This sketch file contains page1 and control, when I only select control to export, the exported slices is true, while I got wrong result when I've chosen both page1 and control. The exported slices is wrong. 
And I found the slices info only diff in rect:
```json
{"x":84,"y":84,"width":50,"height":50} // wrong
{"x":26,"y":26,"width":50,"height":50} // normal
```
I tried to resolve the problem but now I don't have time, so please resolve it

**Comment by qjebbs** [comment]
I don't understand, this plugin doesn't export symbol artboards, you can't even select them in export panel.

**Comment by qjebbs** [comment]
I assume you have change the codes, build your own plugin.

26 & 84 are both right results, because your symbol was put on `(58,58)`, the red rect is at the symbol position of `(26,26)`, `58+26=84`.

If you find the the slice was exported blank, it's a known issue (#10), which will be fixed by latest release.

**Comment by fengqinglingyu** [comment]
OK, I will merge the code and try again.

**Comment by fengqinglingyu** [comment]
I've got the right slices , thanks.
